In [1]:
import numpy as np

In [3]:
a=np.arange(12).reshape(3,4)
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [4]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [5]:
a[b]=0

In [6]:
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:
a=np.arange(12).reshape(3,4)
b1=np.array([False,True,True])
b2=np.array([True,False,True,False])
a[b1,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a=np.array([2,3,4,5])
b=np.array([8,5,4])
c=np.array([5,4,6,8,3])

ax,bx,cx=np.ix_(a,b,c)

In [11]:
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [12]:
bx

array([[[8],
        [5],
        [4]]])

In [13]:
cx

array([[[5, 4, 6, 8, 3]]])

In [14]:
ax.shape,bx.shape,cx.shape

((4, 1, 1), (1, 3, 1), (1, 1, 5))

In [15]:
result=ax+bx*cx

In [16]:
result

array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])

In [17]:
result[3,2,4]

17

In [18]:
a[3]+b[2]*c[4]

17

In [24]:
def ufunc_reduce(ufct,*vectors):
    vs=np.ix_(*vectors)
    r=ufct.identity
    for v in vs:
        r=ufct(r,v)
    return r

In [25]:
ufunc_reduce(np.add,a,b,c)

array([[[15, 14, 16, 18, 13],
        [12, 11, 13, 15, 10],
        [11, 10, 12, 14,  9]],

       [[16, 15, 17, 19, 14],
        [13, 12, 14, 16, 11],
        [12, 11, 13, 15, 10]],

       [[17, 16, 18, 20, 15],
        [14, 13, 15, 17, 12],
        [13, 12, 14, 16, 11]],

       [[18, 17, 19, 21, 16],
        [15, 14, 16, 18, 13],
        [14, 13, 15, 17, 12]]])