In [5]:
import numpy as np

In [6]:
a = np.arange(12)**2                          
i = np.array( [ 1,1,3,8,5 ] )                 
a[i]  

array([ 1,  1,  9, 64, 25])

In [7]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )

In [8]:
a[j]

array([[ 9, 16],
       [81, 49]])

In [9]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
i=np.array([[0,1],[1,2]])

In [13]:
j=np.array([[2,1],[3,3]])

In [14]:
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [18]:
time=np.linspace(20,145,5)
data=np.sin(np.arange(20)).reshape(5,4)
time

array([  20.  ,   51.25,   82.5 ,  113.75,  145.  ])

In [19]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [20]:
ind=data.argmax(axis=0)

In [21]:
ind

array([2, 0, 3, 1])

In [22]:
time_max=time[ind]
data_max=data[ind,range(data.shape[1])]
time_max

array([  82.5 ,   20.  ,  113.75,   51.25])

In [23]:
data_max

array([ 0.98935825,  0.84147098,  0.99060736,  0.6569866 ])

In [24]:
all(data_max==data.max(axis=0))

True

In [25]:
# a[0,1,2,3,4]然后a[[0,0,2]]中第一个0表示，a中的0替换成1，然后第二个0表示将第0个位置的替换成2，于是这个时候a [2,1,2,3,4]
#最后一个a[[0,0,2]]中的2将替换掉a [2,1,2,3,4]中位置为2的为3，于是就有了array([2, 1, 3, 3, 4])
a=np.arange(5)
a[[0,0,2]]=[1,2,3]
a



array([2, 1, 3, 3, 4])

In [1]:
import numpy as np

In [2]:
import numpy.linalg

In [3]:
a=np.array([[1.0,2.0],[3.0,4.0]])
print(a)

[[ 1.  2.]
 [ 3.  4.]]


In [4]:
a.transpose()

array([[ 1.,  3.],
       [ 2.,  4.]])

In [8]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [10]:
u=np.eye(2)

In [11]:
u

array([[ 1.,  0.],
       [ 0.,  1.]])

In [13]:
j=np.array([[0.0,-1.0],[1.0,0.0]])
np.dot(j,j)

array([[-1.,  0.],
       [ 0., -1.]])

In [15]:
np.trace(u)

2.0

In [18]:
y=np.array([[5.0],[7.]])
np.linalg.solve(a,y)

array([[-3.],
       [ 4.]])

In [20]:
np.linalg.eig(j)

(array([ 0.+1.j,  0.-1.j]),
 array([[ 0.70710678+0.j        ,  0.70710678-0.j        ],
        [ 0.00000000-0.70710678j,  0.00000000+0.70710678j]]))

In [22]:
A=np.matrix('1.0 2.0;3.0 4.0')
A

matrix([[ 1.,  2.],
        [ 3.,  4.]])

In [23]:
type(A)

numpy.matrixlib.defmatrix.matrix

In [24]:
A.T

matrix([[ 1.,  3.],
        [ 2.,  4.]])

In [26]:
X=np.matrix('5.0 7.0')
Y=X.T
Y

matrix([[ 5.],
        [ 7.]])

In [27]:
print(A*Y)

[[ 19.]
 [ 43.]]


In [29]:
A=np.arange(12)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
A.shape=(3,4)
M=np.mat(A.copy())
print(type(A)," ",type(M))

<class 'numpy.ndarray'>   <class 'numpy.matrixlib.defmatrix.matrix'>


In [31]:
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [32]:
print(M)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
