In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import Imputer

In [4]:
#生成缺失数据
df=pd.DataFrame(np.random.randn(6,4),columns=['col1','col2','col3','col4'])
df.iloc[1:2,1]=np.nan 
df.iloc[4,3]=np.nan
print(df)

       col1      col2      col3      col4
0  1.735633 -0.405727 -0.515646 -0.928232
1 -0.153444       NaN  0.409557 -0.142822
2  0.102754 -0.249986  0.397377 -1.463378
3  0.010413  1.011308  0.878598  0.021060
4 -0.300253 -0.461628 -1.096326       NaN
5 -1.173275 -0.202096  1.218411  0.611588


In [5]:
#查看哪些缺失值缺失
nan_all=df.isnull()
print(nan_all)

    col1   col2   col3   col4
0  False  False  False  False
1  False   True  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False  False


In [6]:
#查看哪些值缺失
nan_all=df.isnull()
print(nan_all)



    col1   col2   col3   col4
0  False  False  False  False
1  False   True  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False  False


In [7]:
#查看哪些数值缺失
nan_all=df.isnull()
print(nan_all)

    col1   col2   col3   col4
0  False  False  False  False
1  False   True  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False  False


In [8]:
#查看哪些列缺失
nan_col1=df.isnull().any()
nan_col2=df.isnull().all()
print(nan_col1)
print(nan_col2)

col1    False
col2     True
col3    False
col4     True
dtype: bool
col1    False
col2    False
col3    False
col4    False
dtype: bool


In [9]:
#丢弃缺失值
df2=df.dropna()
print(df2)

       col1      col2      col3      col4
0  1.735633 -0.405727 -0.515646 -0.928232
2  0.102754 -0.249986  0.397377 -1.463378
3  0.010413  1.011308  0.878598  0.021060
5 -1.173275 -0.202096  1.218411  0.611588


In [10]:
#使用sklearn将缺失值替换成特定值
nan_model=Imputer(missing_values='NaN',strategy='mean',axis=0)
nan_result=nan_model.fit_transform(df)
print(nan_result)

[[ 1.73563253 -0.40572736 -0.51564555 -0.92823248]
 [-0.15344351 -0.0616257   0.40955741 -0.14282245]
 [ 0.10275375 -0.24998594  0.39737652 -1.46337813]
 [ 0.01041307  1.01130835  0.87859802  0.02106034]
 [-0.300253   -0.46162757 -1.09632613 -0.38035698]
 [-1.17327528 -0.20209599  1.21841091  0.61158781]]


In [11]:
#使用pandas 将缺失值替换成特定值
nan_result_pd1=df.fillna(method='backfill') 
nan_result_pd2=df.fillna(method='bfill',limit=1)
nan_result_pd3=df.fillna(method='pad')
nan_result_pd4=df.fillna(0)
nan_result_pd5=df.fillna({'col2':1,'col4':1.2})
nan_result_pd6=df.fillna(df.mean()['col2':'col4'])

In [18]:
print(nan_result_pd6)

       col1      col2      col3      col4
0  1.735633 -0.405727 -0.515646 -0.928232
1 -0.153444 -0.061626  0.409557 -0.142822
2  0.102754 -0.249986  0.397377 -1.463378
3  0.010413  1.011308  0.878598  0.021060
4 -0.300253 -0.461628 -1.096326 -0.380357
5 -1.173275 -0.202096  1.218411  0.611588


In [ ]:
##异常值处理
df=pd.DataFrame({'col1':[1,120,3,5,2,12,13]})