In [2]:
#3.1数据清洗：缺失值、异常值和重复值处理
#缺失值
import pandas as pd
import numpy as np
from sklearn.preprocessing import Imputer


In [3]:
#生成缺失值

df=pd.DataFrame(np.random.randn(6,4),columns=['coll','col2','col3','col4'])

In [4]:
#生成一份数据
df.iloc[1:2,1]=np.nan
df.iloc[4,3]=np.nan
print(df)


       coll      col2      col3      col4
0  0.405311  0.731973  0.475461 -0.357604
1 -0.825520       NaN -0.218462 -0.324726
2 -0.870500  2.601770 -1.885936 -0.223207
3 -0.270674  1.422113  1.130565  0.032043
4  0.260092  0.008154  0.452140       NaN
5 -1.073805  0.941541 -0.457740  0.152289


In [5]:
nan_all=df.isnull()

In [6]:
print(nan_all)

    coll   col2   col3   col4
0  False  False  False  False
1  False   True  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False  False


In [7]:
nan_col1=df.isnull().any #获得含有NA的列
nan_col2=df.isnull().all #获得全部为NA的列
print(nan_col1)
print(nan_col2)

<bound method DataFrame.any of     coll   col2   col3   col4
0  False  False  False  False
1  False   True  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False  False>
<bound method DataFrame.all of     coll   col2   col3   col4
0  False  False  False  False
1  False   True  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False  False>


In [8]:
#丢弃缺失值
df2=df.dropna()
print(df2)


       coll      col2      col3      col4
0  0.405311  0.731973  0.475461 -0.357604
2 -0.870500  2.601770 -1.885936 -0.223207
3 -0.270674  1.422113  1.130565  0.032043
5 -1.073805  0.941541 -0.457740  0.152289


In [9]:
#使用sklearn 将缺失值替换为特定值
nan_model=Imputer(missing_values='NaN',strategy='mean',axis=0)
#建立替换规则：将值为NaN的缺失值均已均值替换
nan_result=nan_model.fit_transform(df)#应用模型规则
print(nan_result)

[[ 0.40531142  0.73197257  0.47546067 -0.35760442]
 [-0.82551999  1.14111003 -0.21846198 -0.32472608]
 [-0.87050047  2.60177001 -1.88593599 -0.22320699]
 [-0.27067405  1.42211325  1.13056472  0.03204288]
 [ 0.26009214  0.0081537   0.45214007 -0.14424105]
 [-1.0738053   0.94154061 -0.45773957  0.15228936]]


In [10]:
#使用pandas 将缺失值替换成特定值
nan_result_pd1=df.fillna(method='backfill')#用后面的值替换失值
nan_result_pd2=df.fillna(method='bfill',limit=1) #用后面的值代替缺失值，限制每列只能替代一个缺失值
nan_result_pd3=df.fillna(method='pad')
nan_result_pd4=df.fillna(0)
nan_result_pd5=df.fillna({'col2':1.1,'col4':1.2})
nan_result_pd6=df.fillna(df.mean()['col2':'col4'])#用平均数代替，选择各自列的均值替换缺失值

In [16]:
print(nan_result_pd6)

       coll      col2      col3      col4
0  0.405311  0.731973  0.475461 -0.357604
1 -0.825520  1.141110 -0.218462 -0.324726
2 -0.870500  2.601770 -1.885936 -0.223207
3 -0.270674  1.422113  1.130565  0.032043
4  0.260092  0.008154  0.452140 -0.144241
5 -1.073805  0.941541 -0.457740  0.152289


In [12]:
print(nan_result_pd2)

       coll      col2      col3      col4
0  0.405311  0.731973  0.475461 -0.357604
1 -0.825520  2.601770 -0.218462 -0.324726
2 -0.870500  2.601770 -1.885936 -0.223207
3 -0.270674  1.422113  1.130565  0.032043
4  0.260092  0.008154  0.452140  0.152289
5 -1.073805  0.941541 -0.457740  0.152289


In [17]:
##异常值处理
import pandas as pd

In [18]:
df=pd.DataFrame({'col1':[1,120,3,5,2,12,13],
                 'col2':[12,17,31,53,52,32,43]})
print(df)

   col1  col2
0     1    12
1   120    17
2     3    31
3     5    53
4     2    52
5    12    32
6    13    43


In [20]:
#通过Z-Score方法判断异常值
df_zscore=df.copy() #复制一个用来存储Z-score得分的数据框
cols=df.columns #获得数据框的列名
for col in cols:
    df_col=df[col]
    z_score=(df_col-df_col.mean())/df_col.std()#计算每列的Z-score得分
    df_zscore[col]=z_score.abs()>2.2 #判断Z-score得分是否大于2.2，如果是则是True，否则为False

print(df_zscore)  #输出

    col1   col2
0  False  False
1   True  False
2  False  False
3  False  False
4  False  False
5  False  False
6  False  False


In [23]:
df.describe()

col1       col2
count    7.000000   7.000000
mean    22.285714  34.285714
std     43.350180  16.080156
min      1.000000  12.000000
25%      2.500000  24.000000
50%      5.000000  32.000000
75%     12.500000  47.500000
max    120.000000  53.000000

In [24]:
##重复值处理
data1 = ['a', 3]
data2 = ['b', 2]
data3 = ['a', 3]
data4 = ['c', 2]

df=pd.DataFrame([data1,data2,data3,data4],columns=['col1','col2'])
print(df)

  col1  col2
0    a     3
1    b     2
2    a     3
3    c     2


In [25]:
#判断重复值
isDuplicated=df.duplicated() #判断重复数据记录
print(isDuplicated)

0    False
1    False
2     True
3    False
dtype: bool


In [26]:
#删除重复值
new_df1=df.drop_duplicates() #删除数据记录中所有列值相同的记录
new_df2=df.drop_duplicates(['col1']) #删除数据记录中col1值相同的记录
new_df3=df.drop_duplicates(['col2']) 
new_df4=df.drop_duplicates(['col1','col2']) #删除数据记录中指定列（col1/col2）值相同的记录

print(new_df1)


  col1  col2
0    a     3
1    b     2
3    c     2


In [29]:
print(new_df4)

  col1  col2
0    a     3
1    b     2
3    c     2
